### ISSUE TITLE
MusixMatch Api Key

### ISSUE THREAD

**Issue by drakeexqw** [Illusivee/DiscordLyrics#3]
Dude, whose api key is in the project? Can we use the one in the project without changing this thing, that is, without buying ourselves a new api key? Is it okay?
You must also add a License to your project. It is really successful and people can steal your project.

**Comment by logan-mcgee** [comment]
the api key is just extracted from the musixmatch app, just capture traffic using e.g fiddler and you can see the values. it abuses the private api as opposed to being any public api

**Comment by drakeexqw** [comment]
> the api key is just extracted from the musixmatch app, just capture traffic using e.g fiddler and you can see the values. it abuses the private api as opposed to being any public api


dude i don't understand what you are saying
Can I use the api key already in the project? Do I mind or will I be charged?

**Comment by logan-mcgee** [comment]
you can use it just fine, it doesnt affect anything, it wont charge anything considering the service is free

**Comment by drakeexqw** [comment]
Thank you very much.
your project is very successful and I think you should add a license.
